[package]
name = "repline"
repository = "https://github.com/boxdyn/repline"
version = "0.0.7"
authors = ["John <j@soft.fish>"]
edition = "2021"
license = "MIT"
publish = ["soft-fish"]

[dependencies]
crossterm = { version = "0.27.0", default-features = false }
